import { BinItem, DriverItem, TruckItem, OperationalEventItem, PayrollRecord, NotificationItem } from './types';

// Bins dataset matching city operations with green, orange, red fill states
export const INITIAL_BINS: BinItem[] = [
  // Full Bins (Red, 76-100% capacity)
  {
    id: 'B-104',
    name: 'Secunderabad Sector 4 Hub',
    location: 'Secunderabad Phase 2, Main Rd',
    sector: 'Secunderabad',
    fillPercentage: 96,
    color: 'red',
    status: 'Full',
    x: 100,
    y: 95,
    distanceFromTruck: '2.4 km',
    estimatedTime: '6 min',
    priority: 'High',
    isIncludedInRoute: true,
    collectionStatus: 'Pending',
    capacityKg: 1200,
    lastCollected: 'Yesterday 04:30 PM',
    sensorBattery: 92
  },
  {
    id: 'B-208',
    name: 'Gachibowli Tech Park Phase 1',
    location: 'Gachibowli Outer Ring Rd, Gate 3',
    sector: 'Gachibowli',
    fillPercentage: 92,
    color: 'red',
    status: 'Full',
    x: 180,
    y: 65,
    distanceFromTruck: '4.1 km',
    estimatedTime: '10 min',
    priority: 'High',
    isIncludedInRoute: true,
    collectionStatus: 'Pending',
    capacityKg: 1500,
    lastCollected: 'Yesterday 06:10 PM',
    sensorBattery: 88
  },
  {
    id: 'B-312',
    name: 'Begumpet Airport Area Lane 4',
    location: 'Begumpet Old Terminal Rd',
    sector: 'Begumpet',
    fillPercentage: 98,
    color: 'red',
    status: 'Full',
    x: 250,
    y: 110,
    distanceFromTruck: '6.8 km',
    estimatedTime: '14 min',
    priority: 'High',
    isIncludedInRoute: true,
    collectionStatus: 'Pending',
    capacityKg: 1100,
    lastCollected: 'Yesterday 02:00 PM',
    sensorBattery: 79
  },
  {
    id: 'B-405',
    name: 'Madhapur Cyber Towers Junction',
    location: 'Madhapur Main Boulevard',
    sector: 'Madhapur',
    fillPercentage: 88,
    color: 'red',
    status: 'Full',
    x: 320,
    y: 80,
    distanceFromTruck: '8.5 km',
    estimatedTime: '18 min',
    priority: 'High',
    isIncludedInRoute: true,
    collectionStatus: 'Pending',
    capacityKg: 1800,
    lastCollected: 'Yesterday 07:45 PM',
    sensorBattery: 95
  },
  {
    id: 'B-501',
    name: 'Hukumpeta Commercial Square',
    location: 'Hukumpeta Market Line 2',
    sector: 'Secunderabad',
    fillPercentage: 84,
    color: 'red',
    status: 'Full',
    x: 390,
    y: 120,
    distanceFromTruck: '11.2 km',
    estimatedTime: '22 min',
    priority: 'High',
    isIncludedInRoute: true,
    collectionStatus: 'Pending',
    capacityKg: 1400,
    lastCollected: 'Yesterday 03:20 PM',
    sensorBattery: 85
  },

  // Half-Full Bins (Orange, 31-75% capacity)
  {
    id: 'B-101',
    name: 'Jubilee Hills Rd 36 Complex',
    location: 'Jubilee Hills Metro Station Rd',
    sector: 'Jubilee Hills',
    fillPercentage: 58,
    color: 'orange',
    status: 'Half Full',
    x: 140,
    y: 135,
    distanceFromTruck: '3.2 km',
    estimatedTime: '8 min',
    priority: 'Medium',
    isIncludedInRoute: true,
    collectionStatus: 'Pending',
    capacityKg: 1000,
    lastCollected: 'Today 06:00 AM',
    sensorBattery: 91
  },
  {
    id: 'B-202',
    name: 'Banjara Hills Rd 12 Shopping Arc',
    location: 'Banjara Hills Rd 12, Opp Mall',
    sector: 'Banjara Hills',
    fillPercentage: 64,
    color: 'orange',
    status: 'Half Full',
    x: 210,
    y: 155,
    distanceFromTruck: '5.4 km',
    estimatedTime: '12 min',
    priority: 'Medium',
    isIncludedInRoute: true,
    collectionStatus: 'Pending',
    capacityKg: 1200,
    lastCollected: 'Today 07:30 AM',
    sensorBattery: 86
  },
  {
    id: 'B-306',
    name: 'Kukatpally Housing Board Phase 3',
    location: 'KPHB 4th Avenue, Near Flyover',
    sector: 'Kukatpally',
    fillPercentage: 52,
    color: 'orange',
    status: 'Half Full',
    x: 290,
    y: 160,
    distanceFromTruck: '7.9 km',
    estimatedTime: '16 min',
    priority: 'Medium',
    isIncludedInRoute: true,
    collectionStatus: 'Pending',
    capacityKg: 1600,
    lastCollected: 'Today 08:15 AM',
    sensorBattery: 94
  },
  {
    id: 'B-418',
    name: 'Kondapur Botanical Garden Road',
    location: 'Kondapur Heritage Gate',
    sector: 'Kondapur',
    fillPercentage: 68,
    color: 'orange',
    status: 'Half Full',
    x: 360,
    y: 150,
    distanceFromTruck: '10.3 km',
    estimatedTime: '20 min',
    priority: 'Medium',
    isIncludedInRoute: true,
    collectionStatus: 'Pending',
    capacityKg: 1300,
    lastCollected: 'Today 05:45 AM',
    sensorBattery: 82
  },

  // Empty Bins (Green, 0-30% capacity - Excluded from collection route)
  {
    id: 'B-004',
    name: 'Charminar Heritage Plaza',
    location: 'Charminar South Gate Circle',
    sector: 'Old City',
    fillPercentage: 18,
    color: 'green',
    status: 'Empty',
    x: 75,
    y: 170,
    distanceFromTruck: '8.9 km',
    estimatedTime: '19 min',
    priority: 'Low',
    isIncludedInRoute: false,
    collectionStatus: 'Skipped',
    capacityKg: 800,
    lastCollected: 'Today 09:30 AM',
    sensorBattery: 97
  },
  {
    id: 'B-007',
    name: 'Mehdipatnam Bus Terminal Point',
    location: 'Mehdipatnam Depo Gate 1',
    sector: 'Mehdipatnam',
    fillPercentage: 22,
    color: 'green',
    status: 'Empty',
    x: 120,
    y: 45,
    distanceFromTruck: '6.1 km',
    estimatedTime: '13 min',
    priority: 'Low',
    isIncludedInRoute: false,
    collectionStatus: 'Skipped',
    capacityKg: 1000,
    lastCollected: 'Today 10:15 AM',
    sensorBattery: 90
  },
  {
    id: 'B-011',
    name: 'Ameerpet Metro Station South',
    location: 'Ameerpet Junction Ring',
    sector: 'Ameerpet',
    fillPercentage: 14,
    color: 'green',
    status: 'Empty',
    x: 230,
    y: 40,
    distanceFromTruck: '7.5 km',
    estimatedTime: '15 min',
    priority: 'Low',
    isIncludedInRoute: false,
    collectionStatus: 'Skipped',
    capacityKg: 1500,
    lastCollected: 'Today 11:00 AM',
    sensorBattery: 99
  },
  {
    id: 'B-015',
    name: 'Uppal Industrial Corridor',
    location: 'Uppal Ring Road Gate 4',
    sector: 'Uppal',
    fillPercentage: 25,
    color: 'green',
    status: 'Empty',
    x: 350,
    y: 45,
    distanceFromTruck: '12.0 km',
    estimatedTime: '24 min',
    priority: 'Low',
    isIncludedInRoute: false,
    collectionStatus: 'Skipped',
    capacityKg: 1200,
    lastCollected: 'Today 10:45 AM',
    sensorBattery: 89
  },
  {
    id: 'B-019',
    name: 'Dilsukhnagar Market Lane',
    location: 'Dilsukhnagar Main Rd',
    sector: 'Dilsukhnagar',
    fillPercentage: 12,
    color: 'green',
    status: 'Empty',
    x: 420,
    y: 75,
    distanceFromTruck: '14.2 km',
    estimatedTime: '28 min',
    priority: 'Low',
    isIncludedInRoute: false,
    collectionStatus: 'Skipped',
    capacityKg: 1100,
    lastCollected: 'Today 09:00 AM',
    sensorBattery: 93
  }
];

// Waypoints along optimized garbage truck collection route
// Starts at Central Hub -> Full/Half-Full Bins only -> Jawaharnagar Dumping Yard
export const ROUTE_WAYPOINTS = [
  { x: 40, y: 110, label: 'Central Hub Depot' },        // Depot Start
  { x: 100, y: 95, binId: 'B-104', label: 'Secunderabad Hub (Full)' },
  { x: 140, y: 135, binId: 'B-101', label: 'Jubilee Hills (Half-Full)' },
  { x: 180, y: 65, binId: 'B-208', label: 'Gachibowli Tech (Full)' },
  { x: 210, y: 155, binId: 'B-202', label: 'Banjara Hills (Half-Full)' },
  { x: 250, y: 110, binId: 'B-312', label: 'Begumpet Airport (Full)' },
  { x: 290, y: 160, binId: 'B-306', label: 'Kukatpally (Half-Full)' },
  { x: 320, y: 80, binId: 'B-405', label: 'Madhapur Cyber (Full)' },
  { x: 360, y: 150, binId: 'B-418', label: 'Kondapur (Half-Full)' },
  { x: 390, y: 120, binId: 'B-501', label: 'Hukumpeta (Full)' },
  { x: 440, y: 90, label: 'Jawaharnagar Dumping Yard' } // Final Dump Yard
];

// Operational Drivers Dataset
export const INITIAL_DRIVERS: DriverItem[] = [
  {
    id: 'DR-1024',
    empId: 'DR-1024',
    name: 'Raj Kumar',
    status: 'Active',
    isActive: true,
    lastActive: 'Just now',
    currentActivity: 'Collecting waste — Sector 4',
    assignedTruck: 'TRK-204',
    currentLocation: 'Begumpet Sector 4 Hub',
    phone: '+91 98490 23145',
    rating: 4.9,
    shift: 'Morning (06:00 AM – 02:30 PM)',
    experience: '5.2 Years',
    completedTripsToday: 4,
    leaveStatus: 'Pending'
  },
  {
    id: 'DR-1082',
    empId: 'DR-1082',
    name: 'Suresh Kumar',
    status: 'Inactive',
    isActive: false,
    lastActive: '18 minutes ago',
    currentActivity: 'Off duty — Shift completed',
    assignedTruck: 'TRK-108',
    currentLocation: 'Madhapur Central Depot',
    phone: '+91 97011 88421',
    rating: 4.7,
    shift: 'Early Morning (04:30 AM – 01:00 PM)',
    experience: '3.8 Years',
    completedTripsToday: 5,
    leaveStatus: 'None'
  },
  {
    id: 'DR-1105',
    empId: 'DR-1105',
    name: 'Vikram Singh',
    status: 'Active',
    isActive: true,
    lastActive: '1 min ago',
    currentActivity: 'En route to Jawaharnagar Dump Yard',
    assignedTruck: 'TRK-302',
    currentLocation: 'Outer Ring Rd, Gachibowli',
    phone: '+91 99882 11044',
    rating: 4.85,
    shift: 'General (07:00 AM – 03:30 PM)',
    experience: '6.5 Years',
    completedTripsToday: 3,
    leaveStatus: 'None'
  },
  {
    id: 'DR-1044',
    empId: 'DR-1044',
    name: 'Amit Sharma',
    status: 'Active',
    isActive: true,
    lastActive: '3 mins ago',
    currentActivity: 'Compacting waste at Bin B-405',
    assignedTruck: 'TRK-215',
    currentLocation: 'Cyber Towers Junction',
    phone: '+91 98488 44210',
    rating: 4.6,
    shift: 'Morning (06:00 AM – 02:30 PM)',
    experience: '2.4 Years',
    completedTripsToday: 2,
    leaveStatus: 'None'
  },
  {
    id: 'DR-1120',
    empId: 'DR-1120',
    name: 'Ramesh Yadav',
    status: 'Active',
    isActive: true,
    lastActive: 'Just now',
    currentActivity: 'Collecting waste — Jubilee Hills',
    assignedTruck: 'TRK-401',
    currentLocation: 'Jubilee Hills Rd 36',
    phone: '+91 94405 67890',
    rating: 4.92,
    shift: 'Morning (06:00 AM – 02:30 PM)',
    experience: '7.1 Years',
    completedTripsToday: 4,
    leaveStatus: 'None'
  },
  {
    id: 'DR-1090',
    empId: 'DR-1090',
    name: 'Priya Patel',
    status: 'Inactive',
    isActive: false,
    lastActive: '2 hours ago',
    currentActivity: 'On scheduled rest break',
    assignedTruck: 'TRK-105',
    currentLocation: 'Kukatpally Base Station',
    phone: '+91 98660 12345',
    rating: 4.95,
    shift: 'Afternoon (02:00 PM – 10:30 PM)',
    experience: '4.0 Years',
    completedTripsToday: 0,
    leaveStatus: 'Approved'
  },
  {
    id: 'DR-1134',
    empId: 'DR-1134',
    name: 'Dinesh Reddy',
    status: 'Active',
    isActive: true,
    lastActive: '5 mins ago',
    currentActivity: 'Navigating towards Bin B-501',
    assignedTruck: 'TRK-508',
    currentLocation: 'Hukumpeta Market Sq',
    phone: '+91 98499 90012',
    rating: 4.78,
    shift: 'General (07:00 AM – 03:30 PM)',
    experience: '3.2 Years',
    completedTripsToday: 3,
    leaveStatus: 'None'
  },
  {
    id: 'DR-1065',
    empId: 'DR-1065',
    name: 'Manoj Varma',
    status: 'Active',
    isActive: true,
    lastActive: '2 mins ago',
    currentActivity: 'Vehicle hydraulic inspection complete',
    assignedTruck: 'TRK-330',
    currentLocation: 'Secunderabad Maintenance Bay',
    phone: '+91 99491 55678',
    rating: 4.65,
    shift: 'Morning (06:00 AM – 02:30 PM)',
    experience: '4.8 Years',
    completedTripsToday: 2,
    leaveStatus: 'None'
  }
];

// Active Trucks Dataset
export const INITIAL_TRUCKS: TruckItem[] = [
  {
    id: 'TRK-204',
    truckNumber: 'TS 09 UA 2024',
    driverId: 'DR-1024',
    driverName: 'Raj Kumar',
    model: 'Tata Signa 2823.K HD Compactor',
    fuelLevel: 78,
    speed: 38,
    currentTask: 'Collecting Bin B-104',
    nextStop: 'Bin B-208 (Gachibowli Tech)',
    distanceToNext: '2.4 km',
    eta: '6 min',
    totalDistance: '42.6 km',
    routeProgress: 44,
    status: 'Collecting',
    x: 100,
    y: 95,
    headingAngle: 34,
    assignedRouteId: 'RT-HYD-CENTRAL-01'
  },
  {
    id: 'TRK-108',
    truckNumber: 'TS 07 UB 1080',
    driverId: 'DR-1082',
    driverName: 'Suresh Kumar',
    model: 'Ashok Leyland Ecomet Star 1215',
    fuelLevel: 62,
    speed: 0,
    currentTask: 'Idle at Depot',
    nextStop: 'Standby for Afternoon Shift',
    distanceToNext: '0 km',
    eta: '--',
    totalDistance: '28.4 km',
    routeProgress: 100,
    status: 'Idle',
    x: 40,
    y: 110,
    headingAngle: 0,
    assignedRouteId: 'RT-HYD-EAST-02'
  },
  {
    id: 'TRK-302',
    truckNumber: 'TS 08 UC 3020',
    driverId: 'DR-1105',
    driverName: 'Vikram Singh',
    model: 'BharatBenz 1923C Waste Lifter',
    fuelLevel: 84,
    speed: 46,
    currentTask: 'Dumping Yard Transit',
    nextStop: 'Jawaharnagar Dumping Yard',
    distanceToNext: '5.1 km',
    eta: '9 min',
    totalDistance: '56.2 km',
    routeProgress: 88,
    status: 'En Route',
    x: 410,
    y: 100,
    headingAngle: 12,
    assignedRouteId: 'RT-HYD-WEST-03'
  },
  {
    id: 'TRK-215',
    truckNumber: 'TS 09 UD 2155',
    driverId: 'DR-1044',
    driverName: 'Amit Sharma',
    model: 'Tata Prima 3530.K Heavy Carrier',
    fuelLevel: 71,
    speed: 24,
    currentTask: 'Collecting Bin B-405',
    nextStop: 'Bin B-501 (Hukumpeta)',
    distanceToNext: '3.8 km',
    eta: '11 min',
    totalDistance: '35.0 km',
    routeProgress: 60,
    status: 'Collecting',
    x: 320,
    y: 80,
    headingAngle: 75,
    assignedRouteId: 'RT-HYD-NORTH-04'
  },
  {
    id: 'TRK-401',
    truckNumber: 'TS 10 UE 4010',
    driverId: 'DR-1120',
    driverName: 'Ramesh Yadav',
    model: 'Mahindra Blazo X 28 Tipper',
    fuelLevel: 89,
    speed: 32,
    currentTask: 'Collecting Bin B-101',
    nextStop: 'Bin B-202 (Banjara Hills)',
    distanceToNext: '1.9 km',
    eta: '4 min',
    totalDistance: '22.8 km',
    routeProgress: 35,
    status: 'Collecting',
    x: 140,
    y: 135,
    headingAngle: 45,
    assignedRouteId: 'RT-HYD-CENTRAL-02'
  }
];

// Operational Events & Activity Stream
export const INITIAL_EVENTS: OperationalEventItem[] = [
  {
    id: 'EVT-501',
    title: 'Driver Leave Request — Raj Kumar',
    description: 'Raj Kumar requested casual leave for family event.',
    category: 'Driver',
    timestamp: '29 Aug 2026, 09:15 AM',
    relativeTime: '10 minutes ago',
    status: 'Pending',
    driverName: 'Raj Kumar',
    isLeaveRequest: true,
    leaveDates: '29 Aug – 30 Aug 2026',
    location: 'Sector 4 Depot'
  },
  {
    id: 'EVT-502',
    title: 'TRK-204 reached Bin B-104',
    description: 'Hydraulic lift activated for automated bin pickup.',
    category: 'Truck',
    timestamp: '29 Aug 2026, 09:23 AM',
    relativeTime: '2 minutes ago',
    status: 'Completed',
    driverName: 'Raj Kumar',
    truckId: 'TRK-204',
    binId: 'B-104',
    location: 'Hyderabad Sector 4 — Begumpet'
  },
  {
    id: 'EVT-503',
    title: 'Bin B-104 collection completed',
    description: 'Waste collected successfully: 1,150 kg loaded into compactor.',
    category: 'Bin',
    timestamp: '29 Aug 2026, 09:24 AM',
    relativeTime: '1 minute ago',
    status: 'Completed',
    driverName: 'Raj Kumar',
    truckId: 'TRK-204',
    binId: 'B-104',
    location: 'Secunderabad Phase 2'
  },
  {
    id: 'EVT-504',
    title: 'Driver Raj Kumar started shift',
    description: 'Biometric verified at Central Gate, pre-trip safety checklist passed.',
    category: 'Driver',
    timestamp: '29 Aug 2026, 06:30 AM',
    relativeTime: '3 hours ago',
    status: 'Completed',
    driverName: 'Raj Kumar',
    truckId: 'TRK-204',
    location: 'Central Depot Gate 1'
  },
  {
    id: 'EVT-505',
    title: 'Truck TRK-302 entered dumping area',
    description: 'Weighbridge check #1 completed: Gross weight 18,450 kg.',
    category: 'Truck',
    timestamp: '29 Aug 2026, 09:10 AM',
    relativeTime: '15 minutes ago',
    status: 'Completed',
    driverName: 'Vikram Singh',
    truckId: 'TRK-302',
    location: 'Jawaharnagar Dumping Yard'
  },
  {
    id: 'EVT-506',
    title: 'Bin B-312 reached full capacity',
    description: 'IoT Ultrasonic sensor detected 98% volume capacity. Auto-routed to nearest active truck.',
    category: 'Bin',
    timestamp: '29 Aug 2026, 08:45 AM',
    relativeTime: '40 minutes ago',
    status: 'Alert',
    binId: 'B-312',
    location: 'Begumpet Airport Area Lane 4'
  },
  {
    id: 'EVT-507',
    title: 'Vehicle maintenance alert — TRK-330',
    description: 'Brake pad thickness threshold below 15%. Scheduled for evening service bay.',
    category: 'Truck',
    timestamp: '29 Aug 2026, 08:00 AM',
    relativeTime: '1 hour ago',
    status: 'Alert',
    truckId: 'TRK-330',
    driverName: 'Manoj Varma',
    location: 'Secunderabad Maintenance Bay'
  },
  {
    id: 'EVT-508',
    title: 'AI Collection Route Optimized',
    description: 'Dynamic graph recomputed. Avoided Begumpet roadworks, saving 14 mins.',
    category: 'Route',
    timestamp: '29 Aug 2026, 07:15 AM',
    relativeTime: '2 hours ago',
    status: 'Completed',
    location: 'Hyderabad Central Logistics Cloud'
  },
  {
    id: 'EVT-509',
    title: 'Driver Leave Approved — Priya Patel',
    description: 'Medical leave approved for 28 Aug – 29 Aug.',
    category: 'Driver',
    timestamp: '28 Aug 2026, 05:00 PM',
    relativeTime: 'Yesterday',
    status: 'Approved',
    driverName: 'Priya Patel',
    isLeaveRequest: true,
    leaveDates: '28 Aug – 29 Aug 2026',
    location: 'Kukatpally Base'
  }
];

// Employee Payroll Records
export const INITIAL_PAYROLL: PayrollRecord[] = [
  {
    id: 'PAY-1024',
    empId: 'DR-1024',
    driverName: 'Raj Kumar',
    role: 'Lead Heavy Compactor Operator',
    workingDays: 24,
    totalDays: 26,
    attendancePercent: 96,
    overtimeHours: 12,
    leaveDays: 2,
    baseSalary: 24000,
    overtimePay: 3600,
    allowances: 2500,
    deductions: 1600,
    netSalary: 28500,
    status: 'Processed',
    paymentDate: '01 Sep 2026',
    bankAccount: 'HDFC •••• 4029',
    upiId: 'rajkumar.wasteops@okhdfcbank'
  },
  {
    id: 'PAY-1082',
    empId: 'DR-1082',
    driverName: 'Suresh Kumar',
    role: 'Commercial Route Specialist',
    workingDays: 26,
    totalDays: 26,
    attendancePercent: 100,
    overtimeHours: 18,
    leaveDays: 0,
    baseSalary: 23500,
    overtimePay: 5400,
    allowances: 2200,
    deductions: 1500,
    netSalary: 29600,
    status: 'Processed',
    paymentDate: '01 Sep 2026',
    bankAccount: 'SBI •••• 8821',
    upiId: 'sureshkumar@oksbi'
  },
  {
    id: 'PAY-1105',
    empId: 'DR-1105',
    driverName: 'Vikram Singh',
    role: 'Heavy Dump Lifter Driver',
    workingDays: 25,
    totalDays: 26,
    attendancePercent: 96,
    overtimeHours: 14,
    leaveDays: 1,
    baseSalary: 25000,
    overtimePay: 4200,
    allowances: 2500,
    deductions: 1700,
    netSalary: 30000,
    status: 'Paid',
    paymentDate: '25 Aug 2026',
    bankAccount: 'ICICI •••• 1104',
    upiId: 'vikram.singh@okaxis'
  },
  {
    id: 'PAY-1044',
    empId: 'DR-1044',
    driverName: 'Amit Sharma',
    role: 'Junior Route Driver',
    workingDays: 22,
    totalDays: 26,
    attendancePercent: 88,
    overtimeHours: 8,
    leaveDays: 4,
    baseSalary: 21000,
    overtimePay: 2400,
    allowances: 1800,
    deductions: 1400,
    netSalary: 23800,
    status: 'Pending',
    paymentDate: '05 Sep 2026',
    bankAccount: 'Kotak •••• 4421',
    upiId: 'amitsharma2026@kotak'
  },
  {
    id: 'PAY-1120',
    empId: 'DR-1120',
    driverName: 'Ramesh Yadav',
    role: 'Senior Fleet Captain',
    workingDays: 26,
    totalDays: 26,
    attendancePercent: 100,
    overtimeHours: 20,
    leaveDays: 0,
    baseSalary: 26500,
    overtimePay: 6000,
    allowances: 3000,
    deductions: 1800,
    netSalary: 33700,
    status: 'Processed',
    paymentDate: '01 Sep 2026',
    bankAccount: 'Axis •••• 6789',
    upiId: 'ramesh.yadav@axisbank'
  },
  {
    id: 'PAY-1090',
    empId: 'DR-1090',
    driverName: 'Priya Patel',
    role: 'Special Zone Driver',
    workingDays: 23,
    totalDays: 26,
    attendancePercent: 92,
    overtimeHours: 6,
    leaveDays: 3,
    baseSalary: 23000,
    overtimePay: 1800,
    allowances: 2000,
    deductions: 1500,
    netSalary: 25300,
    status: 'Processed',
    paymentDate: '01 Sep 2026',
    bankAccount: 'HDFC •••• 1234',
    upiId: 'priyapatel@okhdfcbank'
  }
];

// Top Notification Alerts
export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'NOTIF-1',
    title: 'Driver Leave Request',
    message: 'Raj Kumar requested leave for 29 Aug – 30 Aug.',
    type: 'warning',
    time: '10 min ago',
    read: false
  },
  {
    id: 'NOTIF-2',
    title: 'Bin Reached Full Capacity',
    message: 'Bin B-104 (Begumpet Sector 4) is at 96% fill level.',
    type: 'alert',
    time: '25 min ago',
    read: false
  },
  {
    id: 'NOTIF-3',
    title: 'Truck Delayed in Traffic',
    message: 'TRK-215 delayed by 12 mins at Cyber Towers Junction.',
    type: 'warning',
    time: '45 min ago',
    read: false
  },
  {
    id: 'NOTIF-4',
    title: 'Vehicle Maintenance Required',
    message: 'TRK-330 scheduled for hydraulic fluid replacement.',
    type: 'info',
    time: '1 hour ago',
    read: true
  },
  {
    id: 'NOTIF-5',
    title: 'Route Optimization Complete',
    message: 'Morning waste collection efficiency up by 18.4%.',
    type: 'success',
    time: '2 hours ago',
    read: true
  }
];
